import type { SiteSeed } from "./types";

/**
 * read.zephyrcode.live — every string below is VERBATIM from
 * /_reference/read.html (BRIEF prime directive: the copy is sacred).
 */
export const readSeed: SiteSeed = {
  site: {
    slug: "read",
    host: "read.zephyrcode.live",
    title: "READ — the shelf with a temperature · ZephyrCode",
    description:
      "Fourteen books on a single heat gradient — from Dinkar's war drums to the dissolving quiet of The Book of Mirdad. Pick by the day you're having, not the canon you're told.",
    accent: "#E85D2A",
    og_image: null,
    nav_order: 5,
  },
  blocks: [
    {
      section: "top",
      kind: "crumb",
      position: 1,
      data: { text: "READ · FIRE → STILLNESS" },
    },
    {
      section: "hero",
      kind: "heading",
      position: 2,
      data: {
        eyebrow: "read.zephyrcode.live",
        h1Html: "The shelf with <em>a temperature.</em>",
        ledeHtml:
          "Fourteen books on one axis — <b>fire to stillness</b>, Dinkar's war drums to the dissolving quiet of Mirdad. Genre is a librarian's problem. The only real question is what the day is asking for. Set the dial; the shelf answers.",
      },
    },
    {
      section: "dial",
      kind: "dial",
      position: 3,
      data: {
        fire: "FIRE — pre-training, pre-war, pre-deadline",
        still: "STILL — after, and above",
        ariaLabel: "Mood: fire to stillness",
        askLines: [
          [0, "the day wants drums. the shelf agrees."],
          [25, "voltage with a spine. musashi is watching your posture."],
          [45, "the bridge: burn, but without smoke."],
          [65, "the emperor and the poet pour you something."],
          [82, "breathe out. the arguments are dissolving."],
          [101, ""],
        ],
      },
    },
    {
      section: "start",
      kind: "picks",
      position: 4,
      data: {
        k: "START THIS WEEK · THE FOUR-BOOK IGNITION",
        picks: [
          ["Rashmirathi", "THE CENTER OF GRAVITY"],
          ["The Book of Five Rings", "THE TRAINING PARTNER"],
          ["Bhagavad Gita", "THE HINGE"],
          ["Siddhartha", "THE EXHALE"],
        ],
        tail: "Read the fire standing up and the stillness sitting down. There is no third posture; that's the whole curriculum.",
      },
    },
  ],
  books: [
    {
      position: 1,
      title: "Haldighati",
      author: "Shyam Narayan Pandey",
      pos: 0.02,
      register: "FIRE",
      lang: "HINDI",
      note: "Hooves, steel, and a horse that out-acts most protagonists. Pure veer rasa, zero apologies.",
    },
    {
      position: 2,
      title: "Rashmirathi",
      author: "Ramdhari Singh Dinkar",
      pos: 0.07,
      register: "FIRE",
      lang: "HINDI",
      note: "Karna's answer to the accident of birth, delivered at sword-length. Krishna's warning canto alone is worth the shelf. Start here.",
    },
    {
      position: 3,
      title: "Parashuram ki Prateeksha",
      author: "Dinkar",
      pos: 0.12,
      register: "FIRE",
      lang: "HINDI",
      note: "A nation scolded awake after 1962. Reads like a slap that loves you.",
    },
    {
      position: 4,
      title: "Ram ki Shakti Puja",
      author: "Suryakant Tripathi 'Nirala'",
      pos: 0.18,
      register: "FIRE",
      lang: "HINDI",
      note: "Even gods rehearse. Ram confronting his own weakness on the eve of war — dense, towering, worth the climb.",
    },
    {
      position: 5,
      title: "Hunkar",
      author: "Dinkar",
      pos: 0.22,
      register: "FIRE",
      lang: "HINDI",
      note: "The warm-up drum. Short blasts of voltage for mornings that start heavy.",
    },
    {
      position: 6,
      title: "The Book of Five Rings",
      author: "Musashi · tr. Cleary",
      pos: 0.28,
      register: "FIRE",
      lang: "EN",
      note: "Sixty duels undefeated, and his deepest advice is about attention. Talks straight to the gloves. Reread yearly.",
    },
    {
      position: 7,
      title: "Thus Spoke Zarathustra",
      author: "Friedrich Nietzsche",
      pos: 0.34,
      register: "FIRE",
      lang: "EN · HARD",
      note: "Osho's number one. Prose-poetry that bites if grabbed — read in passages, like lifting, never to failure.",
    },
    {
      position: 8,
      title: "Kurukshetra",
      author: "Dinkar",
      pos: 0.45,
      register: "BRIDGE",
      lang: "HINDI",
      note: "Violence cross-examined on a bed of arrows. Where the fire poems start asking questions.",
    },
    {
      position: 9,
      title: "Bhagavad Gita",
      author: "tr. Eknath Easwaran",
      pos: 0.52,
      register: "BRIDGE",
      lang: "EN",
      note: "A warrior talked back into the fight and taught to burn without smoke. If you read one book off this shelf, this.",
    },
    {
      position: 10,
      title: "Meditations",
      author: "Marcus Aurelius",
      pos: 0.62,
      register: "BRIDGE",
      lang: "EN",
      note: "An emperor's private notes on not becoming the thing he ruled. Written for an audience of one; somehow about you.",
    },
    {
      position: 11,
      title: "Madhushala",
      author: "Harivansh Rai Bachchan",
      pos: 0.68,
      register: "BRIDGE",
      lang: "HINDI",
      note: "Intoxication as theology. Sip, don't gulp — every quatrain is a full pour.",
    },
    {
      position: 12,
      title: "Siddhartha",
      author: "Hermann Hesse",
      pos: 0.78,
      register: "STILL",
      lang: "EN · EASY",
      note: "Enlightenment by way of everything the monks renounce. The warm door into the quiet wing.",
    },
    {
      position: 13,
      title: "Enlightenment: The Only Revolution",
      author: "Osho on Ashtavakra",
      pos: 0.86,
      register: "STILL",
      lang: "EN",
      note: "The hammer that whispers: you are already free — stop applying. One discourse at a time, preferably horizontal.",
    },
    {
      position: 14,
      title: "The Book of Mirdad",
      author: "Mikhail Naimy",
      pos: 0.95,
      register: "STILL",
      lang: "EN · SHORT",
      note: "The quiet book that ends arguments by dissolving the arguer. Why Osho is Osho.",
    },
  ],
};
